[package]
name = "spending-tracker-api"
version = "0.1.0"
authors = ["Bryant Deters <bryantdeters@gmail.com>"]

[dependencies]
actix-web = "0.7.14"
actix = "0.7.6"
serde = "1.0.80"
serde_json = "1.0.33"
serde_derive = "1.0.80"